package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

    private int idAsignatura;
    private String asignatura;
    private Set inscribes = new HashSet(0);
    private Set preguntas = new HashSet(0);
    private Set presentas = new HashSet(0);
    private Set respondes = new HashSet(0);

    public Asignatura() {
    }

    public Asignatura(int idAsignatura, String asignatura) {
        this.idAsignatura = idAsignatura;
        this.asignatura = asignatura;
    }

    public Asignatura(int idAsignatura, String asignatura, Set inscribes, Set preguntas, Set presentas, Set respondes) {
        this.idAsignatura = idAsignatura;
        this.asignatura = asignatura;
        this.inscribes = inscribes;
        this.preguntas = preguntas;
        this.presentas = presentas;
        this.respondes = respondes;
    }

    public int getIdAsignatura() {
        return this.idAsignatura;
    }

    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }

    public String getAsignatura() {
        return this.asignatura;
    }

    public void setAsignatura(String asignatura) {
        this.asignatura = asignatura;
    }

    public Set getInscribes() {
        return this.inscribes;
    }

    public void setInscribes(Set inscribes) {
        this.inscribes = inscribes;
    }

    public Set getPreguntas() {
        return this.preguntas;
    }

    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }

    public Set getPresentas() {
        return this.presentas;
    }

    public void setPresentas(Set presentas) {
        this.presentas = presentas;
    }

    public Set getRespondes() {
        return this.respondes;
    }

    public void setRespondes(Set respondes) {
        this.respondes = respondes;
    }

}
