package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

/**
 * Asocia generated by hbm2java
 */
public class Asocia implements java.io.Serializable {

    private AsociaId id;
    private Pregunta pregunta;
    private Respuesta respuesta;
    private boolean correcta;

    public Asocia() {
    }

    public Asocia(AsociaId id, Pregunta pregunta, Respuesta respuesta, boolean correcta) {
        this.id = id;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
        this.correcta = correcta;
    }

    public AsociaId getId() {
        return this.id;
    }

    public void setId(AsociaId id) {
        this.id = id;
    }

    public Pregunta getPregunta() {
        return this.pregunta;
    }

    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

    public Respuesta getRespuesta() {
        return this.respuesta;
    }

    public void setRespuesta(Respuesta respuesta) {
        this.respuesta = respuesta;
    }

    public boolean isCorrecta() {
        return this.correcta;
    }

    public void setCorrecta(boolean correcta) {
        this.correcta = correcta;
    }

}
