package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name = "Estudiante")
public class Estudiante implements java.io.Serializable {

    @Id
    @Column(name = "codigo_estudiante")
    private long codigoEstudiante;
    @Column(name = "nombre_estudiante")
    private String nombreEstudiante;
    @Column(name = "contrasena")
    private String contrasena;
    private Set inscribes = new HashSet(0);
    private Set presentas = new HashSet(0);
    private Set respondes = new HashSet(0);

    public Estudiante() {
    }

    public Estudiante(long codigoEstudiante, String nombreEstudiante, String contrasena) {
        this.codigoEstudiante = codigoEstudiante;
        this.nombreEstudiante = nombreEstudiante;
        this.contrasena = contrasena;
    }

    public Estudiante(long codigoEstudiante, String nombreEstudiante, String contrasena, Set inscribes, Set presentas, Set respondes) {
        this.codigoEstudiante = codigoEstudiante;
        this.nombreEstudiante = nombreEstudiante;
        this.contrasena = contrasena;
        this.inscribes = inscribes;
        this.presentas = presentas;
        this.respondes = respondes;
    }

    public long getCodigoEstudiante() {
        return this.codigoEstudiante;
    }

    public void setCodigoEstudiante(long codigoEstudiante) {
        this.codigoEstudiante = codigoEstudiante;
    }

    public String getNombreEstudiante() {
        return this.nombreEstudiante;
    }

    public void setNombreEstudiante(String nombreEstudiante) {
        this.nombreEstudiante = nombreEstudiante;
    }

    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    public Set getInscribes() {
        return this.inscribes;
    }

    public void setInscribes(Set inscribes) {
        this.inscribes = inscribes;
    }

    public Set getPresentas() {
        return this.presentas;
    }

    public void setPresentas(Set presentas) {
        this.presentas = presentas;
    }

    public Set getRespondes() {
        return this.respondes;
    }

    public void setRespondes(Set respondes) {
        this.respondes = respondes;
    }

}
