package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

/**
 * Inscribe generated by hbm2java
 */
public class Inscribe implements java.io.Serializable {

    private InscribeId id;
    private Asignatura asignatura;
    private Estudiante estudiante;
    private short grupo;

    public Inscribe() {
    }

    public Inscribe(InscribeId id, Asignatura asignatura, Estudiante estudiante, short grupo) {
        this.id = id;
        this.asignatura = asignatura;
        this.estudiante = estudiante;
        this.grupo = grupo;
    }

    public InscribeId getId() {
        return this.id;
    }

    public void setId(InscribeId id) {
        this.id = id;
    }

    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public short getGrupo() {
        return this.grupo;
    }

    public void setGrupo(short grupo) {
        this.grupo = grupo;
    }

}
