package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

/**
 * InscribeId generated by hbm2java
 */
public class InscribeId implements java.io.Serializable {

    private long codigoEstudiante;
    private int idAsignatura;

    public InscribeId() {
    }

    public InscribeId(long codigoEstudiante, int idAsignatura) {
        this.codigoEstudiante = codigoEstudiante;
        this.idAsignatura = idAsignatura;
    }

    public long getCodigoEstudiante() {
        return this.codigoEstudiante;
    }

    public void setCodigoEstudiante(long codigoEstudiante) {
        this.codigoEstudiante = codigoEstudiante;
    }

    public int getIdAsignatura() {
        return this.idAsignatura;
    }

    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof InscribeId)) {
            return false;
        }
        InscribeId castOther = (InscribeId) other;

        return (this.getCodigoEstudiante() == castOther.getCodigoEstudiante())
                && (this.getIdAsignatura() == castOther.getIdAsignatura());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getCodigoEstudiante();
        result = 37 * result + this.getIdAsignatura();
        return result;
    }

}
