package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta implements java.io.Serializable {

    private int idPregunta;
    private String pregunta;
    private Set respondes = new HashSet(0);
    private Set asocias = new HashSet(0);
    private Set presentas = new HashSet(0);
    private Set asignaturas = new HashSet(0);

    public Pregunta() {
    }

    public Pregunta(int idPregunta, String pregunta) {
        this.idPregunta = idPregunta;
        this.pregunta = pregunta;
    }

    public Pregunta(int idPregunta, String pregunta, Set respondes, Set asocias, Set presentas, Set asignaturas) {
        this.idPregunta = idPregunta;
        this.pregunta = pregunta;
        this.respondes = respondes;
        this.asocias = asocias;
        this.presentas = presentas;
        this.asignaturas = asignaturas;
    }

    public int getIdPregunta() {
        return this.idPregunta;
    }

    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }

    public String getPregunta() {
        return this.pregunta;
    }

    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }

    public Set getRespondes() {
        return this.respondes;
    }

    public void setRespondes(Set respondes) {
        this.respondes = respondes;
    }

    public Set getAsocias() {
        return this.asocias;
    }

    public void setAsocias(Set asocias) {
        this.asocias = asocias;
    }

    public Set getPresentas() {
        return this.presentas;
    }

    public void setPresentas(Set presentas) {
        this.presentas = presentas;
    }

    public Set getAsignaturas() {
        return this.asignaturas;
    }

    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }

}
