package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

/**
 * PresentaId generated by hbm2java
 */
public class PresentaId implements java.io.Serializable {

    private long codigoEstudiante;
    private int idAsignatura;
    private int idPregunta;

    public PresentaId() {
    }

    public PresentaId(long codigoEstudiante, int idAsignatura, int idPregunta) {
        this.codigoEstudiante = codigoEstudiante;
        this.idAsignatura = idAsignatura;
        this.idPregunta = idPregunta;
    }

    public long getCodigoEstudiante() {
        return this.codigoEstudiante;
    }

    public void setCodigoEstudiante(long codigoEstudiante) {
        this.codigoEstudiante = codigoEstudiante;
    }

    public int getIdAsignatura() {
        return this.idAsignatura;
    }

    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }

    public int getIdPregunta() {
        return this.idPregunta;
    }

    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PresentaId)) {
            return false;
        }
        PresentaId castOther = (PresentaId) other;

        return (this.getCodigoEstudiante() == castOther.getCodigoEstudiante())
                && (this.getIdAsignatura() == castOther.getIdAsignatura())
                && (this.getIdPregunta() == castOther.getIdPregunta());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getCodigoEstudiante();
        result = 37 * result + this.getIdAsignatura();
        result = 37 * result + this.getIdPregunta();
        return result;
    }

}
