package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Presenta generated by hbm2java
 */
public class Presenta implements java.io.Serializable {

    private PresentaId id;
    private Asignatura asignatura;
    private Estudiante estudiante;
    private Pregunta pregunta;
    private Date fecha;
    private String lugar;

    public Presenta() {
    }

    public Presenta(PresentaId id, Asignatura asignatura, Estudiante estudiante, Pregunta pregunta, Date fecha, String lugar) {
        this.id = id;
        this.asignatura = asignatura;
        this.estudiante = estudiante;
        this.pregunta = pregunta;
        this.fecha = fecha;
        this.lugar = lugar;
    }

    public PresentaId getId() {
        return this.id;
    }

    public void setId(PresentaId id) {
        this.id = id;
    }

    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public Pregunta getPregunta() {
        return this.pregunta;
    }

    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

}
