package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

/**
 * Responde generated by hbm2java
 */
public class Responde implements java.io.Serializable {

    private RespondeId id;
    private Asignatura asignatura;
    private Estudiante estudiante;
    private Pregunta pregunta;
    private Respuesta respuesta;

    public Responde() {
    }

    public Responde(RespondeId id, Asignatura asignatura, Estudiante estudiante, Pregunta pregunta, Respuesta respuesta) {
        this.id = id;
        this.asignatura = asignatura;
        this.estudiante = estudiante;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
    }

    public RespondeId getId() {
        return this.id;
    }

    public void setId(RespondeId id) {
        this.id = id;
    }

    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public Pregunta getPregunta() {
        return this.pregunta;
    }

    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

    public Respuesta getRespuesta() {
        return this.respuesta;
    }

    public void setRespuesta(Respuesta respuesta) {
        this.respuesta = respuesta;
    }

}
