package com.informatica.preguntas.modelo;
// Generated 21-may-2017 11:18:12 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta implements java.io.Serializable {

    private int idRespuesta;
    private String respuesta;
    private Set asocias = new HashSet(0);
    private Set respondes = new HashSet(0);

    public Respuesta() {
    }

    public Respuesta(int idRespuesta, String respuesta) {
        this.idRespuesta = idRespuesta;
        this.respuesta = respuesta;
    }

    public Respuesta(int idRespuesta, String respuesta, Set asocias, Set respondes) {
        this.idRespuesta = idRespuesta;
        this.respuesta = respuesta;
        this.asocias = asocias;
        this.respondes = respondes;
    }

    public int getIdRespuesta() {
        return this.idRespuesta;
    }

    public void setIdRespuesta(int idRespuesta) {
        this.idRespuesta = idRespuesta;
    }

    public String getRespuesta() {
        return this.respuesta;
    }

    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    public Set getAsocias() {
        return this.asocias;
    }

    public void setAsocias(Set asocias) {
        this.asocias = asocias;
    }

    public Set getRespondes() {
        return this.respondes;
    }

    public void setRespondes(Set respondes) {
        this.respondes = respondes;
    }

}
